version: '3'

services:
  
  schedule-api:
    build:
      context: "./backend/schedule/"
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000 
    volumes:
      - ./backend/schedule:/src
    environment:
      - ENVIRON

  schedule-front:
    build:
      context: "./frontend/schedule/"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/schedule/src:/app
    command: sh -c "npm run dev"
  
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd